import { createRoot } from "react-dom/client";
import "./src/index.css";
import { App } from "./src/App";
export * from "./src/App";
export * from "./src/lib/api";
export * from "./src/lib/routes";
export * from "./src/components/DialogShell";
export * from "./src/components/NotificationCenter";
const root = document.getElementById("root");
if (root) createRoot(root).render(<App />);
